#include "libftprintf.h"

int main()
{
    int c;
    int i;

    c = 0;
		i = ft_printf("[|%022.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
        i = printf("[|%022.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
        
		c++;
		printf("\n\n");
		i = ft_printf("[|%0.100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
        i = printf ("[|%0.100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		printf("\n\n");
		i = ft_printf("[|%.022.1500s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
        i = printf ("[|%.022.1500s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%22.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%22.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%22.1500s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%22.1500s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%.s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%.s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%5s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%5s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%100s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%100s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%-22.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%-22.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%-100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%-100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%-100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%-100s.15s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%-22.s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%-22.s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%-.s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%-.s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%-5s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%-5s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("[|%-225s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("[|%-225s|]\n", "Hello  *");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\t%s\n", "coucou, ca va?");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("  Or\t:\t%s\n", "coucou, ca va?");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%s\" is visible.\n", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf ("  Or\t:\tThe string \"%s\" is visible.\n", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
        printf("\n\n");
		 
		i = ft_printf("  Or\t:\tThe string \"%s%s%s\" is visible.\n", "TRALALA", "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%s%s%s\" is visible.\n", "TRALALA", "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		char *null_s = NULL;
		i = ft_printf("  Or\t:\tThe Null string \"%s\" is visible.\n", null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%s\" is visible.\n", null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%s%s%s\" is visible.\n", null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%s%s%s\" is visible.\n", null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%s%s%s%s\" is visible.\n", null_s, null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%s%s%s%s\" is visible.\n", null_s, null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%*s\" is visible.\n", 0, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%*s\" is visible.\n", 0, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
         return 0;
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%36s%*s%98.5s\" is visible.\n", "TRALALA", 30, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%36s%*s%98.5s\" is visible.\n", "TRALALA", 30, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%s%*s%s\" is visible.\n", "TRALALA", 0, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%s%*s%s\" is visible.\n", "TRALALA", 0, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-s%-s%-s%-s\" is visible.\n", null_s, null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-s%-s%-s%-s\" is visible.\n", null_s, null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%-*s\" is visible.\n", 0, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%-*s\" is visible.\n", 0, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%-*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%-*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%36s%-*s%-98.5s\" is visible.\n", "TRALALA", 30, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%36s%-*s%-98.5s\" is visible.\n", "TRALALA", 30, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%-*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%-*s\" is visible.\n", 985, "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe string \"%-s%-*s%-s\" is visible.\n", "TRALALA", 0, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe string \"%-s%-*s%-s\" is visible.\n", "TRALALA", 0, "TRALALA", "TRALALA");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-0s%-0s%0-s%-0s\" is visible.\n", null_s, null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-0s%-0s%0-s%-0s\" is visible.\n", null_s, null_s, null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-0s%-0s%\" is visible.\n", null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-0s%-0s%\" is visible.\n", null_s, null_s);
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-0s%-0s%\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-0s%-0s%\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-0.s%-0.s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-0.s%-0.s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-.0s%-.0s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-.0s%-.0s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-.000s%-.000s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-.000s%-.000s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-000.000s%00-0.000s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-000.000s%00-0.000s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%-985.000s%159-0.000s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%-985.000s%159-0.000s\" is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
		i = ft_printf("  Or\t:\tThe Null string \"%$-0.s$%-0.s\" $is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		i = printf("  Or\t:\tThe Null string \"%$-0.s$%-0.s\" $is visible.\n", "hellos", "Ezz");
		//printf("\nI= %d, TestN: %d\n", i, c);
		c++;
		 printf("\n\n");
}